- hosts: automatiza-projeto
  tasks:
  - name: Instalando o python3, virtualenv e depedencias mysql
    apt:
      pkg:
      - python3
      - python3-pip
      - libmysqlclient-dev
      - python3-dev
#      - libssl-dev
#      - libffi-dev
#      - pkg-config
      update_cache: yes
    become: true

  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/ssdvd/app-cadastro-django.git
      dest: /home/ubuntu/djangoapp
      version: main
      force: yes

  - name: Instalando dependencias com pip
    pip:
      virtualenv: /home/ubuntu/djangoapp/venv
      requirements: /home/ubuntu/djangoapp/requirements.txt

  - name: iniciando o servidor
    shell: 'source /home/ubuntu/djangoapp/venv/bin/activate; nohup python3 /home/ubuntu/djangoapp/manage.py runserver 0.0.0.0:8000 &' 